site_name: MKDocs Demo Document
theme:
  name: material
  font:
    text: Work Sans
  language: en
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: indigo
    scheme: default
    toggle:
      icon: material/brightness-2
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: indigo
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  icon:
    # logo: material/school
    logo: fontawesome/solid/book-open
    # repo: fontawesome/brands/git-alt
  features:
    - content.code.copy
    - content.code.select
    # - navigation.tabs
    - navigation.path
    # - search.suggest
    # - search.highlight

# repo_name: squidfunk/mkdocs-material
# site_url: ""
# site_url: 'https://docs.example.com/'
# use_directory_urls: false

# extra_css:
#   - css/custom.css

extra:
  version:
    provider: mike

markdown_extensions:
  # for admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # for code highlight
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # for diagram
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # for icons
  # - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg