name: main
on:
  push:
    branches:
    - main
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Cache
      uses: actions/cache@v2
      with:
        key: ${{ github.ref }}
        path: .cache
    - run: pip install mkdocs-material
    - run: mkdocs deploy gh-deploy --force
